<?php

namespace NJHSGDBD\DcatExt\Form;

use Dcat\Admin\Admin;
use Dcat\Admin\Form\Field;

class SwitchModifyField extends Field
{
    protected $view = 'njhsgdbd.dcat-ext::field.form-switch';

    protected $attributes = [
        'data-open'  => '#5cb85c',
        'data-close' => '#d9534f',
    ];

    public function render()
    {
        $this->style();
        return parent::render(); // TODO: Change the autogenerated stub
    }

    public function style()
    {
        Admin::style(<<<CSS
.bootstrap-switch-nowrap span{
    white-space: nowrap;
}
.bootstrap-switch-handle-off,.bootstrap-switch-handle-on{
    font-size: 9px !important;
    font-weight: bold;
}
CSS
        );
    }

    public function noPadding(): static
    {
        $this->setFieldClass('p-0');
        return $this;
    }
}
