name: Publish to Packagist

on:
  push:
    branches:
      - main
      - master # 根据实际主分支名称调整

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Notify Packagist
      run: |
        curl -X POST https://packagist.org/api/update-package \
          -H "Content-Type: application/json" \
          -d '{
            "repository": "'${{ github.repository }}'"
          }' \
          -u "${{ secrets.PACKAGIST_USERNAME }}:${{ secrets.PACKAGIST_TOKEN }}"
